apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one-deployement
  labels:
    app: app-one
spec:
  replicas: 1
  selector: # to identify the Pods to manage.
    matchLabels: # with these labels 
      app: app-one
  template: # template of Pod Manifest: it is exactly the same schema as a Pod manifest, except it is nested and does not have an apiVersion or kind
    metadata:
      labels:
        app: app-one
    spec:
      containers:
      - name: app-one
        image: paulbouwer/hello-kubernetes:1
        ports: #
        - containerPort: 8080 #
        env:
          - name: MESSAGE
            value: "Hello from app1."

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-two-deployement
  labels:
    app: app-two
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: app-two
  template: 
    metadata:
      labels:
        app: app-two
    spec:
      containers:
      - name: app-two
        image: paulbouwer/hello-kubernetes:1
        env:
          - name: MESSAGE
            value: "Hello from app2."

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-three-deployement
  labels:
    app: app-three
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: app-three
  template: 
    metadata:
      labels:
        app: app-three
    spec:
      containers:
      - name: app-three
        image: paulbouwer/hello-kubernetes:1
        env:
          - name: MESSAGE
            value: "Hello from app 3."

