apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one-deployement
  labels:
    app: app-one
spec:
  replicas: 1
  selector: # to identify the Pods to manage.
    matchLabels: 
      app: app-one
  template: # template of Pod Manifest: it is exactly the same schema as a Pod manifest, except it is nested and does not have an apiVersion or kind
    metadata:
      labels:
        app: app-one
    spec:
      containers:
      - name: app-one
        image: paulbouwer/hello-kubernetes:1
        # ports:
        # - containerPort: 8080
        env:
          - name: MESSAGE
            value: "Hello from app1."