apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-agocd-application 
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://gitlab-webservice-default.gitlab.svc:8181/root/lpuchol.git
    targetRevision: HEAD
    path: bonus/
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true