
VM_BOX = "bento/debian-12"
MASTER_NODE = "lpucholS"

MASTER_IP = "192.168.56.110"

VM_PROVIDER = "virtualbox"

VM_MEMORY = 2048
VM_CPUS = 3

Vagrant.configure("2") do |config|
  
  # Machine 1: lpucholS (Server)
  config.vm.define MASTER_NODE do |server|

    # configure the box
    server.vm.box = VM_BOX
    server.vm.hostname = MASTER_NODE
    server.vm.network "private_network", bridge: "eth1", ip: MASTER_IP
    server.vm.provider VM_PROVIDER do |vb|
      vb.memory = VM_MEMORY
      vb.cpus = VM_CPUS
    end
    # Provision K3s controller installation
    # --flannel-iface=eth1: Override default flannel interface consequently set the service on ip of his node
    server.vm.provision "shell", inline: <<-SHELL
	  export PATH=$PATH:/sbin
      sudo apt-get update
      sudo apt-get install -y curl net-tools

      # sudo curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --flannel-iface=eth1" sh -
      # sudo curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --node-ip=192.168.56.110 --flannel-iface=eth1 --write-kubeconfig-mode=644" sh -
      # sudo curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --node-external-ip=192.168.56.110 --write-kubeconfig-mode=644" sh -
	  curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-external-ip=192.168.56.110" K3S_TOKEN="" sh -s -
      # sudo chmod 644 /etc/rancher/k3s/k3s.yaml

	  mkdir /home/vagrant/.kube 2> /dev/null
	  export KUBECONFIG=/home/vagrant/.kube/config
      sudo k3s kubectl config view --raw > "$KUBECONFIG"
	  chmod 600 "$KUBECONFIG"
	  echo "export KUBECONFIG=/home/vagrant/.kube/config" >> /home/vagrant/.bashrc
	  sudo chown -R vagrant /home/vagrant/.kube


    #   sudo systemctl stop nftables
    #   sudo systemctl disable nftables

      echo "alias k=kubectl" >> .bashrc
      echo "export PATH=$PATH:/sbin" >> /home/vagrant/.bashrc

      sudo kubectl apply -f /vagrant/confs/Deployments/deployments.yaml
      sudo kubectl apply -f /vagrant/confs/Services/services.yaml
      sudo kubectl apply -f /vagrant/confs/Ingress/ingress.yaml
      
      source /home/vagrant/.bashrc
    SHELL
  end
end