
Vagrant.configure("2") do |config|
  
  # Machine 1: lpucholS (Server)
  config.vm.define "lpucholS" do |server|

    # configure the box
    server.vm.box = "debian/bookworm64"
    server.vm.hostname = "lpucholS"
    server.vm.network "public_network", bridge: "eth1", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 3
    end
    # Provision K3s controller installation
    # --flannel-iface=eth1: Override default flannel interface consequently set the service on ip of his node
    server.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y curl net-tools
      sudo systemctl stop nftables
      sudo systemctl disable nftables
      sudo curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --flannel-iface=eth1" sh -
      sudo chmod 644 /etc/rancher/k3s/k3s.yaml
      echo "alias k=kubectl" >> .bashrc
      export PATH=$PATH:/sbin
    SHELL
  end
end