apiVersion: v1
kind: Service
metadata:
  name: app-one
spec:
  selector:
    app.kubernetes.io/name: app-one
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: app-two
spec:
  selector:
    app.kubernetes.io/name: app-two
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: app-three
spec:
  selector:
    app.kubernetes.io/name: app-three
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80