apiVersion: v1
kind: Service
metadata:
  name: app-one-service
spec:
  selector:
    app: app-one
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

# apiVersion: v1
# kind: Service
# metadata:
#   name: app-one-service
# spec:
#   selector:
#     app: app-one
#   type: NodePort
#   ports:
#     - protocol: TCP
#       port: 80
#       nodePort: 30601
#       # targetPort: 8080

