apiVersion: v1
kind: Service
metadata:
  name: app-one-service
spec:
  selector:
    app.kubernetes.io/name: app-one
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30001

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: app-two-service
# spec:
#   selector:
#     app.kubernetes.io/name: app-two
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: app-three-service
# spec:
#   selector:
#     app.kubernetes.io/name: app-three
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80